# Generated by Django 4.2.4 on 2023-08-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0002_alter_speaker_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='phone_number',
            field=models.URLField(blank=True, null=True),
        ),
    ]
