# Generated by Django 4.2.4 on 2023-08-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0003_alter_speaker_id_alter_speaker_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
